# Generated by Django 4.1.4 on 2022-12-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Profile',
        ),
    ]
